- .gitignore
- appspec.yml
- out/production/resources/application.yml
- scripts/deploy.sh
- 배포 시 health check 실패로 Nginx 설정 제외하도록 수정
> [Build] 배포 스크립트 수정 - Nginx 설정 변경

- src/main/java/dnd/diary/HealthCheckController.java
> [TEST] health check

- src/main/java/dnd/diary/enumeration/Result.java
- src/main/java/dnd/diary/exception/CommonRestExceptionHandler.java
- src/main/java/dnd/diary/exception/CustomException.java
- src/main/java/dnd/diary/response/CustomResponseEntity.java
> [Feat] 공통 응답, 예외 처리 클래스 추가

- build.gradle
- src/main/java/dnd/diary/config/CorsConfig.java
- src/main/java/dnd/diary/config/Jwt/JwtAccessDeniedHandler.java
- src/main/java/dnd/diary/config/Jwt/JwtAuthenticationEntryPoint.java
- src/main/java/dnd/diary/config/Jwt/JwtFilter.java
- src/main/java/dnd/diary/config/Jwt/JwtSecurityConfig.java
- src/main/java/dnd/diary/config/Jwt/JwtUserService.java
- src/main/java/dnd/diary/config/Jwt/SecurityUtil.java
- src/main/java/dnd/diary/config/Jwt/TokenProvider.java
- src/main/java/dnd/diary/config/RedisConfig.java
- src/main/java/dnd/diary/config/RedisDao.java
- src/main/java/dnd/diary/config/RestTemplateConfig.java
- src/main/java/dnd/diary/config/SecurityConfig.java
- src/main/java/dnd/diary/controller/UserController.java
- src/main/java/dnd/diary/domain/user/Authority.java
- src/main/java/dnd/diary/domain/user/User.java
- src/main/java/dnd/diary/dto/UserDto.java
- src/main/java/dnd/diary/exception/CommonRestExceptionHandler.java
- src/main/java/dnd/diary/repository/UserRepository.java
- src/main/java/dnd/diary/service/UserService.java
> [FEAT] 유저 서비스 구현 (회원가입 / 로그인)

- .gitignore
Reverts dnd-side-project/dnd-8th-4-backend#41
> Revert "TEST 임시제외"

- src/main/java/dnd/diary/controller/UserController.java
- src/main/java/dnd/diary/controller/content/ContentController.java
- src/main/java/dnd/diary/domain/content/Content.java
- src/main/java/dnd/diary/domain/content/ContentImage.java
- src/main/java/dnd/diary/dto/content/ContentDto.java
- src/main/java/dnd/diary/repository/content/ContentImageRepository.java
- src/main/java/dnd/diary/repository/content/ContentRepository.java
- src/main/java/dnd/diary/service/content/ContentService.java
> [FEAT] 게시글 작성 기능 구현

- src/main/java/dnd/diary/controller/group/GroupController.java
- src/main/java/dnd/diary/controller/group/GroupValidator.java
- src/main/java/dnd/diary/domain/group/Group.java
- src/main/java/dnd/diary/domain/user/UserJoinGroup.java
- src/main/java/dnd/diary/enumeration/Result.java
- src/main/java/dnd/diary/repository/group/UserJoinGroupRepository.java
- src/main/java/dnd/diary/response/group/GroupCreateResponse.java
- src/main/java/dnd/diary/response/group/GroupListResponse.java
- src/main/java/dnd/diary/response/group/GroupUpdateResponse.java
- src/main/java/dnd/diary/service/group/GroupService.java
- 기존에 그룹 생성 시 호스트 유저 가입 처리 누락 부분 추가했습니당 🤢
**Sample Request**
```
{
"groupName" : "테스트 그룹 1",
"groupNote" : "테스트 그룹 1 소개입니당"
}
```
**Sample Response**
```
{
"code": 0,
"message": "성공",
"data": {
"groupId": 1,
"groupName": "테스트 그룹 1",
"groupNote": "테스트 그룹 1 소개입니당",
"groupImageUrl": null,
"groupCreateUserId": 1,
"groupCreatedAt": "2023.02.19 16:25:19",
"groupModifiedAt": "2023.02.19 16:25:19",
"groupMemberList": [
{
"userId": 1,
"userEmail": "smegyeong.gamil.com",
"userNickname": "심미경",
"userJoinGroupDatedAt": "2023.02.19 16:25:19"
}
]
}
}
```
> [Feat] 그룹 생성 시 호스트 유저 그룹 가입 처리 및 Response 수정

- src/main/java/dnd/diary/enumeration/Result.java
- src/main/java/dnd/diary/repository/content/EmotionRepository.java
- src/main/java/dnd/diary/response/CustomResponseEntity.java
- src/main/java/dnd/diary/service/content/EmotionService.java
- 눌려있을경우 공감 삭제
- 안눌려있을경우 공감 남기기
> [FEAT] 공감 남기기 구현 수정

- src/main/java/dnd/diary/controller/content/CommentController.java
- src/main/java/dnd/diary/dto/content/CommentDto.java
- src/main/java/dnd/diary/repository/content/CommentRepository.java
- src/main/java/dnd/diary/repository/content/EmotionRepository.java
- src/main/java/dnd/diary/service/content/CommentService.java
> [FEAT] 댓글 조회 API 구현

- src/main/java/dnd/diary/dto/content/CommentDto.java
- src/main/java/dnd/diary/dto/content/ContentDto.java
- src/main/java/dnd/diary/service/content/CommentService.java
- src/main/java/dnd/diary/service/content/ContentService.java
> [FEAT] 댓글 조회 기능 구현

- src/main/java/dnd/diary/controller/UserController.java
- src/main/java/dnd/diary/controller/group/GroupController.java
- src/main/java/dnd/diary/domain/group/Group.java
- src/main/java/dnd/diary/domain/user/UserJoinGroup.java
- src/main/java/dnd/diary/enumeration/Result.java
- src/main/java/dnd/diary/repository/UserRepository.java
- src/main/java/dnd/diary/response/group/GroupCreateResponse.java
- src/main/java/dnd/diary/response/group/GroupListResponse.java
- src/main/java/dnd/diary/response/group/GroupUpdateResponse.java
- src/main/java/dnd/diary/response/user/UserSearchResponse.java
- src/main/java/dnd/diary/service/UserService.java
- src/main/java/dnd/diary/service/group/GroupService.java
- [그룹 목록 조회 시 최신 업데이트 순 정렬](https://github.com/dnd-side-project/dnd-8th-4-backend/commit/48f05f3cb04782e08cadf73bbe90d0c1443434a1)
- [[Feat] 그룹 삭제 API 수정 및 구성원 탈퇴 처리](https://github.com/dnd-side-project/dnd-8th-4-backend/commit/2677996325ed82dd075b48bc12045ba1c4b7b4de)
- [[Refactor] 그룹 삭제/구성원 탈퇴 처리 Sofft Delete 수정](https://github.com/dnd-side-project/dnd-8th-4-backend/commit/d6fb80331b1d329f1aaaec954bb51852da18ad9a)
- [[Feat] 유저 검색(이메일, 닉네임) API 추가](https://github.com/dnd-side-project/dnd-8th-4-backend/pull/78/commits/435327f8bb3656328a534808893b870e5f973119)
- [[Fix] 그룹 수정 오류 수정](https://github.com/dnd-side-project/dnd-8th-4-backend/pull/78/commits/0cd788139de08c0c80177b1ff4cd69f6530938b4)
> [Feat] 그룹 목록 조회 업데이트 순 정렬 추가, 그룹 삭제 API 수정

- src/main/java/dnd/diary/controller/content/ContentController.java
- src/main/java/dnd/diary/domain/content/ContentImage.java
- src/main/java/dnd/diary/dto/content/ContentDto.java
- src/main/java/dnd/diary/repository/content/ContentImageRepository.java
- src/main/java/dnd/diary/service/content/ContentService.java
- 이미지 추가 가능 (null 허용)
- 이미지 삭제 가능 (null 허용)
- 글/위치 수정 (글은 NotNull)
> [FEAT] 글 수정 API 구현

- src/main/java/dnd/diary/controller/content/ContentController.java
- src/main/java/dnd/diary/dto/content/ContentDto.java
- src/main/java/dnd/diary/enumeration/Result.java
- src/main/java/dnd/diary/repository/content/ContentRepository.java
- src/main/java/dnd/diary/service/content/ContentService.java
> [FEAT, CHORE] 그룹 피드 조회 API 구현

- src/main/java/dnd/diary/config/RedisDao.java
- src/main/java/dnd/diary/dto/content/ContentDto.java
- src/main/java/dnd/diary/service/content/ContentService.java
- 해당 피드를 한번 조회했던 유저라면 조회수가 더 이상 올라가지 않게끔 수정
> 피드 상세 보기 API Redis 추가 구현

- src/main/java/dnd/diary/controller/user/UserController.java
- src/main/java/dnd/diary/dto/content/ContentDto.java
- src/main/java/dnd/diary/dto/userDto/UserDto.java
- src/main/java/dnd/diary/repository/content/BookmarkRepository.java
- src/main/java/dnd/diary/service/user/UserService.java
> [FEAT, CHORE] 북마크한 글 조회 API 구현

- build.gradle
- src/main/java/dnd/diary/config/GeometryUtil.java
- src/main/java/dnd/diary/config/Location.java
- src/main/java/dnd/diary/controller/content/ContentController.java
- src/main/java/dnd/diary/domain/content/Content.java
- src/main/java/dnd/diary/dto/content/ContentDto.java
- src/main/java/dnd/diary/enumeration/Direction.java
- src/main/java/dnd/diary/service/content/ContentService.java
- Content에 Point column 추가
- 글 작성시 위도 경도 값이 존재할경우 Point까지 save
- 내 그룹 피드 지도에서 보아보기 API 구현
> [FEAT] 내 그룹 피드 지도 모아보기 API 구현

- src/main/java/dnd/diary/enumeration/Result.java
- src/main/java/dnd/diary/repository/content/BookmarkRepository.java
- src/main/java/dnd/diary/service/content/BookmarkService.java
> [FEAT, CHORE] 북마크 한 피드 중복 등록 방지 처리 및 기타수정

- src/main/java/dnd/diary/controller/content/CommentController.java
- src/main/java/dnd/diary/dto/content/CommentDto.java
- src/main/java/dnd/diary/dto/content/ContentDto.java
- src/main/java/dnd/diary/service/content/CommentService.java
> [FEAT] 피드 공감 리스트 조회 API 추가

- src/main/java/dnd/diary/dto/content/ContentDto.java
- src/main/java/dnd/diary/enumeration/Result.java
- src/main/java/dnd/diary/repository/content/BookmarkRepository.java
- src/main/java/dnd/diary/response/CustomResponseEntity.java
- src/main/java/dnd/diary/service/content/BookmarkService.java
- src/main/java/dnd/diary/service/content/ContentService.java
- 북마크 등록 후 한번 더 호출시 북마크 삭제
- 전체 그룹 피드 리스트 조회시 북마크 등록 여부 추가
> [FEAT] 북마크 API 수정

- src/main/java/dnd/diary/dto/userDto/UserDto.java
- src/main/java/dnd/diary/service/user/UserService.java
> [FEAT] 북마크, 작성한 글, 댓글 단 글 조회시 Response 수정

- src/main/java/dnd/diary/config/Jwt/JwtAuthenticationEntryPoint.java
- src/main/java/dnd/diary/controller/user/UserController.java
- src/main/java/dnd/diary/enumeration/Result.java
- src/main/java/dnd/diary/exception/CustomException.java
- src/main/java/dnd/diary/exception/CustomExceptionResponse.java
- src/main/java/dnd/diary/response/CustomResponseEntity.java
- src/main/java/dnd/diary/service/user/UserService.java
> [FEAT] 로그아웃 API 구현

- src/main/java/dnd/diary/controller/user/UserController.java
- src/main/java/dnd/diary/dto/userDto/UserDto.java
- src/main/java/dnd/diary/service/user/UserService.java
- 이미지가 null 도 가능하게끔 프로필 수정, 회원가입 수정
> [FEAT] 회원가입 API 기능 수정 - close #149

- src/main/java/dnd/diary/dto/content/ContentDto.java
- src/main/java/dnd/diary/service/content/ContentService.java
- 피드 조회시 북마크 등록 상태, 이모션 상태 추가
- 피드 검색시 userId 추가
> [FEAT] 피드 조회, 피드 검색시 Response 추가

- src/main/java/dnd/diary/controller/user/UserController.java
- src/main/java/dnd/diary/dto/userDto/UserDto.java
- src/main/java/dnd/diary/service/user/UserService.java
> [FEAT] 클라이언트 요청사항에 맞게 API 변경

- src/main/java/dnd/diary/DiaryApplication.java
- src/main/java/dnd/diary/config/RedisCacheConfig.java
- src/main/java/dnd/diary/service/content/ContentService.java
> [FEAT] 피드 상세보기 cache 적용

- src/main/java/dnd/diary/service/content/ContentService.java
- Redis Look Aside + Write Around 전략
> [FEAT] 피드 상세 보기 성능 개선

- src/main/java/dnd/diary/dto/userDto/UserDto.java
- src/main/java/dnd/diary/repository/content/BookmarkRepository.java
- src/main/java/dnd/diary/service/user/UserService.java
- 글이 삭제된 게시글이 북마크 한 글에 포함되어 있을경우 오류나던 상황 해결
- 해당 Response에서 북마크ID제거
> [FIX] 북마크한 글 오류 해결

- src/main/java/dnd/diary/repository/content/BookmarkRepository.java
- src/main/java/dnd/diary/repository/content/ContentImageRepository.java
- src/main/java/dnd/diary/repository/group/UserJoinGroupRepository.java
- src/main/java/dnd/diary/repository/user/UserRepository.java
- src/main/java/dnd/diary/service/content/ContentService.java
- Service 단에서 구현된 Query를 Repository로 전환
> [REFACTOR] 피드 수정 / 지도 피드 모아보기 API  

- src/main/java/dnd/diary/dto/content/ContentDto.java
> [FEAT] 지도 피드 상세보기 API 변경

- src/main/java/dnd/diary/dto/content/ContentDto.java
- 게시글에 이미지가 없을 경우 기본이미지 삽입 (현재는 임시이미지)
> [FEAT] 지도 상세보기 API 추가

- src/main/java/dnd/diary/controller/content/ContentController.java
- src/main/java/dnd/diary/dto/content/ContentDto.java
- src/main/java/dnd/diary/repository/content/ContentRepository.java
- src/main/java/dnd/diary/service/content/ContentService.java
- 중복되는 게시글 문제 해결
- 상세 조회시 location으로 param 변경
> [FEAT] 내 그룹 피드 지도 모아보기, 지도 피드 상세조회 수정

- src/main/java/dnd/diary/domain/content/Content.java
- src/main/java/dnd/diary/dto/content/ContentDto.java
- src/main/java/dnd/diary/service/content/ContentService.java
- Content Update Refactor
- 갓미경 폼 미쳤다;;;
> [REFACTOR] 갓미경표 업데이트 코드 리팩터

- src/main/java/dnd/diary/dto/userDto/UserDto.java
> [FEAT] 마이페이지 글 조회 API 관련 추가

- src/main/java/dnd/diary/repository/content/CommentRepository.java
- src/main/java/dnd/diary/service/user/UserService.java
> [REFACTOR] 내가 댓글 단 글NativeQuery 수정

- src/main/java/dnd/diary/dto/content/CommentDto.java
- src/main/java/dnd/diary/service/content/CommentService.java
- src/main/java/dnd/diary/service/content/ContentService.java
> [FEAT] 피드 댓글 조회 API

- src/main/java/dnd/diary/dto/content/ContentDto.java
> [FEAT] 지도 피드 상세보기 API

- src/main/java/dnd/diary/controller/content/EmotionController.java
- src/main/java/dnd/diary/domain/content/Emotion.java
- src/main/java/dnd/diary/enumeration/Result.java
- src/main/java/dnd/diary/service/content/EmotionService.java
- 보내는 emotionStatus에 따라 등록, 삭제, 수정 됨
1. 공감을 하지 않았을때 등록
2. 등록된 공감과 같은 공감을 날렸을때 삭제
3. 등록된 공감과 다른 공감을 날렸을때 수정
> [FEAT] 공감하기 로직 변경

- src/main/java/dnd/diary/domain/group/Notification.java
- src/main/java/dnd/diary/repository/group/NotificationRepository.java
- src/main/java/dnd/diary/service/content/EmotionService.java
- 공감 삭제시 알림의 emotion 컬럼 null로 변경
> [FEAT] 공감 알림 변경
